In [1]:
import numpy as np

In [3]:
a1 = np.array([[1,2,3,4],[7,8,9,0]])

In [4]:
a1

array([[1, 2, 3, 4],
       [7, 8, 9, 0]])

In [5]:
a1*a1

array([[ 1,  4,  9, 16],
       [49, 64, 81,  0]])

In [6]:
a1-a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
1/a1

C:\Users\MADHUKUMAR V\AppData\Local\Temp\ipykernel_3408\2609805251.py:1: RuntimeWarning: divide by zero encountered in divide
  1/a1


array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.14285714, 0.125     , 0.11111111,        inf]])

In [8]:
a1**3

array([[  1,   8,  27,  64],
       [343, 512, 729,   0]], dtype=int32)

In [9]:
# indexing array


In [10]:
import numpy as np


In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[1:5]

array([1, 2, 3, 4])

In [14]:

arr2 = arr[1:9]

In [15]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr2[:]= 66

In [17]:
arr2

array([66, 66, 66, 66, 66, 66, 66, 66])

In [18]:
arr

array([ 0, 66, 66, 66, 66, 66, 66, 66, 66,  9])

In [19]:
arr_copy =arr2.copy()

In [20]:
arr_copy

array([66, 66, 66, 66, 66, 66, 66, 66])

In [21]:
 arr3 = np.array([[1,2,3,4],[5,6,7,8],[4,5,6,7]])

In [22]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [23]:
arr3[0]

array([1, 2, 3, 4])

In [24]:
arr[1]

66

In [25]:
arr3[1]

array([5, 6, 7, 8])

In [26]:
arr3[2]

array([4, 5, 6, 7])

In [27]:
arr3[1:2]

array([[5, 6, 7, 8]])

In [28]:
arr3[0][2]

3

In [29]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [30]:
arr3[:2,2:]

array([[3, 4],
       [7, 8]])

In [31]:
arr3[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [32]:
arr0 = np.zeros(10)

In [33]:
arr0


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
arr_h=np.zeros((10,10))

In [68]:
arr_h

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
arr_h.shape[1]

10

In [78]:
aa=arr_h.shape[1]

In [79]:
aa

10

In [88]:
for i in range(10,10):
    arr_h[i]=i

In [89]:
arr_h

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [92]:
arr_h[[0,1,2,3,4,5]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [93]:
for i in range(10,10):
    arr_h[i]=i
    

In [94]:
arr_h

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [95]:
arr3=arr_h.copy()

In [96]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
arr3[1]=[2,5,6,9,9,6,6,6,6,6]

In [102]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 5., 6., 9., 9., 6., 6., 6., 6., 6.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [110]:
arr3

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])